name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "{ PYTHON_VERSION }"
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4
        with:
          python-version: ${{ matrix.python-version }}
      - name: UV Build
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
