name: UV

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  uv:
    name: python
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      matrix:
        python-version:
          - "{ PYTHON_VERSION }"
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python
        run: uv python install
      - name: pyTest
        run: uv run pytest tests
      - name: Ruff (check)
        run: uv run ruff check
      - name: Ruff (format)
        run: uv run ruff format --diff --check
      - name: Ty
        run: uv run ty check
      - name: Troml
        run: uv run troml check
      - name: Run SonarQube
        uses: sonarsource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
