name: UV

on:
  push:
    branches:
      - main

jobs:
  uv:
    name: python
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      matrix:
        python-version:
          - "{ PYTHON_VERSION }"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python
        run: uv python install
      - name: Run pyTest
        run: uv run pytest tests
      - name: Run Ruff
        run: uv run ruff check
      - name: Run Ty
        run: uv run ty check
      - name: Run SonarQube
        uses: sonarsource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
